name: KontrexAPI
author: DerEisverkaeufer
version: 1.0
main: net.kontrex.api.KontrexAPI

commands:
     gamemode:
       aliases: [gm]
       permission: kontrex.gamemode
     teleport:
       aliases: [tp]
       permission: kontrex.teleport
     time:
       aliases: [tm]
       permission: kontrex.time
     devmode:
       aliases: [dev]
       permission: kontrex.devmode